# Generated by Django 5.1.1 on 2024-09-13 15:00

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('day', multiselectfield.db.fields.MultiSelectField(choices=[('monday', '월요일'), ('tuesday', '화요일'), ('wednesday', '수요일'), ('thursday', '목요일'), ('friday', '금요일'), ('saturday', '토요일'), ('sunday', '일요일')], max_length=56)),
                ('label', models.CharField(max_length=200)),
                ('realert', models.BooleanField(default=True)),
            ],
        ),
    ]
