# Generated by Django 5.1.1 on 2024-09-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_alarm_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='realert',
        ),
    ]
